version: "3.7"
services:
  server:
    container_name: server_api
    build: server
    image: server_api:latest
    ports:
      - "8081:8081"
    volumes:
      - ./server:/node_modules
      - ./server:/home/server
      - ./static:/home/server/static
    deploy:
      replicas: 1
#  server_db:
#    container_name: cakes
#    image: postgres:13.3
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: revolution67rus
#      PGDATA: /var/lib/postgresql/data
#      POSTGRES_DB: cakeShop
#    volumes:
#      - ./docker-volumes/postgres/:/var/lib/postgresql/data
#    ports:
#      - "54321:5432"
#    deploy:
#      replicas: 1

  cabinet-client:
    container_name: cabinet-client
    build: cabinet-client
    env_file:
      - ./cabinet-client/.env
    ports:
      - "5173:80"
    deploy:
      replicas: 1
    environment:
      VIRTUAL_HOST: kassandras-cake.ru

  cabinet-admin:
    container_name: cabinet-admin
    build: cabinet-admin
    env_file:
      - ./cabinet-admin/.env
    ports:
      - "3000:80"
    deploy:
      replicas: 1
    environment:
      VIRTUAL_HOST: admin-panel.kassandras-cake.ru

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./static:/data/static
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
