version: "3.7"
services:
  server:
    container_name: server_api
    build: server
    image: server_api:latest
    ports:
      - "8081:8081"
    volumes:
      - ./server:/node_modules
      - ./server:/home/server
      - ./static:/home/server/static
    deploy:
      replicas: 1

  cabinet-client:
    container_name: cabinet-client
    build: cabinet-client
    env_file:
      - ./cabinet-client/.env
    ports:
      - "5173:80"
    deploy:
      replicas: 1

  cabinet-admin:
    container_name: cabinet-admin
    build: cabinet-admin
    env_file:
      - ./cabinet-admin/.env
    ports:
      - "3000:80"
    deploy:
      replicas: 1

#  web:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./static:/data/static
#    restart: always
#    privileged: true
