const Router = require("express");
const router = new Router();
const deviceRouter = require("./deviceRouter");
const typeRouter = require("./typeRouter");
const userRouter = require("./userRouter");
const fillingRouter = require("./fillingRouter");
const basketRouter = require("./basketRouter");
const processingRouter = require("./orderProcessingRouter");
const analyticsRouter = require("./analyticsRouter");
const calendarRouter = require("./calendarRouter");
const decorRouter = require("./decorRouter");
const biscuitRouter = require("./biscuitRouter");
const ratingRouter = require("./ratingsRouter");
const todoRouter = require("./todoListRouter");
const uniqUsersRouter = require("./uniqUsersRouter");
const seoRouter = require("./seoRouter");

router.use("/user", userRouter);
router.use("/device", deviceRouter);
router.use("/type", typeRouter);
router.use("/filling", fillingRouter);
router.use("/basket", basketRouter);
router.use("/order_processing", processingRouter);
router.use("/analytics", analyticsRouter);
router.use("/calendar", calendarRouter);
router.use("/biscuit", biscuitRouter);
router.use("/decor", decorRouter);
router.use("/ratings", ratingRouter);
router.use("/todoList", todoRouter);
router.use("/uniqUsers", uniqUsersRouter);
router.use('/seo', seoRouter);

module.exports = router;
