export const enum EnpointsEnum {
  CREATE_CAKE = '/device/shop/create',
  GET_CAKES = '/device/shop/getAll',
  GET_ONE_CAKE = '/device/shop/get/:id',
  REMOVE_CAKE = '/device/delete',
  EDIT_CAKE = '/device/shop/update',
  GET_RECIPE = '/device/shop/admin/getOne',
  REGISTRATION_USER = '/user/registration',
  LOGIN_USER = '/user/login',
  AUTHORIZATION_USER = '/user/auth',
  CREATE_TYPE = '/type/create',
  CREATE_FILLING = '/filling/create',
  GET_TYPES = '/type/getAll',
  GET_FILLINGS = '/filling/getAll',
  DELETE_TYPES = '/type/remove',
  DELETE_FILLINGS = '/filling/remove',
  CREATE_INDIVIDUAL_ORDER = '/order/create',
  CREATE_USER_ORDER = '/basket/create',
}
